In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences 
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good devloper',
        'understand the meaning of words',
        'your videos are good'
        
        
        ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good devloper',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Define the Vocabulary size 

voc_size =10000

In [5]:
### one hot representation for every word

one_hot_rep = [one_hot(words,voc_size) for words in sent]


In [6]:
one_hot_rep


[[1999, 2460, 5032, 5360],
 [1999, 2460, 5032, 4366],
 [1999, 7192, 5032, 3064],
 [8433, 4128, 5502, 7158, 202],
 [8433, 4128, 5502, 7158, 3607],
 [3110, 1999, 7092, 5032, 4602],
 [7845, 8374, 6013, 7158]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np


In [12]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 1999 2460 5032 5360]
 [   0    0    0    0 1999 2460 5032 4366]
 [   0    0    0    0 1999 7192 5032 3064]
 [   0    0    0 8433 4128 5502 7158  202]
 [   0    0    0 8433 4128 5502 7158 3607]
 [   0    0    0 3110 1999 7092 5032 4602]
 [   0    0    0    0 7845 8374 6013 7158]]


In [13]:
### Feature representation
dim=10

In [15]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 243ms/step


array([[[-0.04860721,  0.00779939,  0.04480067, -0.03518759,
         -0.02184474,  0.02086724,  0.02075842, -0.01800735,
          0.034001  , -0.03743421],
        [-0.04860721,  0.00779939,  0.04480067, -0.03518759,
         -0.02184474,  0.02086724,  0.02075842, -0.01800735,
          0.034001  , -0.03743421],
        [-0.04860721,  0.00779939,  0.04480067, -0.03518759,
         -0.02184474,  0.02086724,  0.02075842, -0.01800735,
          0.034001  , -0.03743421],
        [-0.04860721,  0.00779939,  0.04480067, -0.03518759,
         -0.02184474,  0.02086724,  0.02075842, -0.01800735,
          0.034001  , -0.03743421],
        [ 0.03370516, -0.00447744,  0.01162832, -0.02719622,
         -0.01996994,  0.00115279, -0.02728174, -0.02184804,
          0.03033734,  0.02040308],
        [ 0.02717086,  0.04681544,  0.0241383 , -0.01645046,
         -0.01783658, -0.00823893,  0.00028127,  0.02126196,
          0.00597221,  0.01819745],
        [-0.01068176, -0.02783868,  0.0111229 ,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 1999, 2460, 5032, 5360])

In [21]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 12ms/step


array([[-0.04860721,  0.00779939,  0.04480067, -0.03518759, -0.02184474,
         0.02086724,  0.02075842, -0.01800735,  0.034001  , -0.03743421],
       [-0.04860721,  0.00779939,  0.04480067, -0.03518759, -0.02184474,
         0.02086724,  0.02075842, -0.01800735,  0.034001  , -0.03743421],
       [-0.04860721,  0.00779939,  0.04480067, -0.03518759, -0.02184474,
         0.02086724,  0.02075842, -0.01800735,  0.034001  , -0.03743421],
       [-0.04860721,  0.00779939,  0.04480067, -0.03518759, -0.02184474,
         0.02086724,  0.02075842, -0.01800735,  0.034001  , -0.03743421],
       [ 0.03370516, -0.00447744,  0.01162832, -0.02719622, -0.01996994,
         0.00115279, -0.02728174, -0.02184804,  0.03033734,  0.02040308],
       [ 0.02717086,  0.04681544,  0.0241383 , -0.01645046, -0.01783658,
        -0.00823893,  0.00028127,  0.02126196,  0.00597221,  0.01819745],
       [-0.01068176, -0.02783868,  0.0111229 ,  0.01431691, -0.04926997,
         0.01754363,  0.00422367,  0.0469026 